#!/bin/bash
export WANDB_API_KEY=""
export WANDB_ENTITY=
export WANDB_PROJECT=

export KAGGLE_USERNAME=""
export KAGGLE_KEY=""

export PYTEST_DIR="/data0/"

export EXPERIMENT_NAME=
export HF_USERNAME=""
export HF_TOKEN=
export HF_CACHE_DIR=$PYTEST_DIR

export TOKENIZERS_PARALLELISM=False

export CODE_DIR=/devcode/GATE-private/
export PROJECT_DIR="/data0/"
export EXPERIMENT_NAME_PREFIX="gate-exp-0"
export EXPERIMENTS_ROOT_DIR=$PROJECT_DIR
export EXPERIMENTS_DIR=$PROJECT_DIR
export EXPERIMENT_DIR=$PROJECT_DIR
export DATASET_DIR=$PYTEST_DIR
export MODEL_DIR=$PROJECT_DIR

