name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Process repository name
      id: repo-name
      run: |
        echo "::set-output name=lowercase_repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/$(echo ${{ steps.repo-name.outputs.lowercase_repo }}):${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/$(echo ${{ steps.repo-name.outputs.lowercase_repo }}):latest
