name: Python Lint and Format

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'
  pull_request:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 autoflake

    - name: Run isort
      run: isort -l 79 .

    - name: Run black
      run: black -l 79 .

    - name: Run flake8
      run: autoflake --remove-all-unused-imports --remove-unused-variables --recursive . 
      
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Apply isort, black, and flake8"
        git remote set-url origin https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/your-username/your-repo.git
        git push
