name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip3 install -r requirements.txt
    - name: Build Sphinx documentation
      run: |
        cd docs  # Replace 'docs' with the path to your Sphinx documentation directory
        make html

    - name: Deploy to docs branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b docs-pages
        rm -rf *  # Remove all files except the .git directory
        mv docs/_build/html/* .  # Move the built documentation to the repository root
        git add .
        git commit -m "Update documentation"
        git remote set-url origin https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/your-username/your-repo.git
        git push -u origin docs-pages --force
