name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx  # Add any other required dependencies, e.g., sphinx_rtd_theme or sphinx_autodoc_typehints

    - name: Build Sphinx documentation
      run: |
        cd docs  # Replace 'docs' with the path to your Sphinx documentation directory
        make html

    - name: Deploy to docs branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b docs-pages
        rm -rf ./*  # Remove all files except the .git directory
        mv ./docs/_build/html/* ./  # Move the built documentation to the repository root
        git add .
        git commit -m "Update documentation"
        git push -u origin docs-pages --force
